AllCops:
  Exclude:
    - '.kitchen/**/*'
    - 'metadata.rb'
    - 'test/cookbooks/fake/metadata.rb'
    - 'Berksfile'
    - 'test/cookbooks/**/*'

LineLength:
  Max: 200

WordArray:
  Enabled: false

FileName:
  Enabled: false

RegexpLiteral:
  Enabled: false
